import React, { useState, useEffect } from "react";
import Head from "next/head";
import axios from "axios";

import { ProductCard } from "../components/ProductCard";
import { API_URL } from '../utils/constants';

import "./styles/main.styles.css";
import { Navbar } from '../components/Navbar/Navbar';



type ProductsType = {
  id: number,
  title: string,
  image: string
}


export default function IndexPage() {
  const [products, setProducts] = useState<T[]>([]);

  /*
    Fetch product data from API_URL, set the appropiate data for useState,
    you can use the proposed axios or fetch with useEffect or 
    if you want to try reactQuery or useSWR, awesome!
  */


  return (
    <>
      <Head>
        <title>Products Shop - PGD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='flip-card'>
        <div className='flip-card-inner'>
          <div className='flip-card-front'>
            <h2>You Better Flip Me</h2>
          </div>
          <div className='flip-card-back'>
            <h2>
              Check the products before the timer ends. Keep in mind the timer
              (which is random)
            </h2>
          </div>
        </div>
      </div>

      {products.length ? (
        <div className='container'>
          {
            /* Render the products using ProductCard component */
          }
        </div>
      ) : (
        <div className='dots-bars-2'></div>
      )}
    </>
  );
}
